### ISSUE TITLE
Neither U2F nor FIDO2 is offered for Chrome 89 / Ubuntu 20.04

### ISSUE THREAD

**Issue by sgofferj** [akeeba/loginguard#100]
Please read the README.md in the repository's root and the support resources before submitting an issue.

### Steps to reproduce the issue
Try to set up 2FA

### Expected result
Loginguard should offer Fido2 and U2F

### Actual result
Loginguard did NOT offer Fido2 nor U2F

### Troubleshooting already performed
None.

### System information
Ubuntu 20.04
Chrome 89.0.4389.82 (Official Build) (64-bit)

#### Mandatory information

* **Joomla! version**: 3.9.25
* **PHP version**: 7.4.14
* **Am I using HTTPS**: Yes, through reverse proxy. 
* **Server Operating System**: Linux 1a1a2a07d284 4.14.214-118.339.amzn1.x86_64 #1 SMP Sun Jan 10 10:40:32 UTC 2021 x86_64
* **My device's Operating System**: Ubuntu
* **My device's Operating System version**: 20.04
* **Browser**: Chrome
* **Browser version**: 89.0.4389.82 (Official Build) (64-bit)

#### Good to have information

You can skip some or all of this information. However, the more information you provide the faster and better we can help.

* **MySQL version**: 5.5.5-10.5.8-MariaDB-1:10.5.8+maria~focal
* **Server type**: nginx
* **Server version**: 1.19.5
* **Hosting company / Local server**: AWS
* **Server Operating System version**: Linux 1a1a2a07d284 4.14.214-118.339.amzn1.x86_64 #1 SMP Sun Jan 10 10:40:32 UTC 2021 x86_64

### Additional comments
![Screenshot_20210310_120915](https://user-images.githubusercontent.com/3258466/110613587-1e67d500-819a-11eb-822e-ace73bf1e7a4.png)

**Comment by nikosdion** [comment]
Might be a stupid question, but have you enabled the corresponding plugin?

**Comment by nikosdion** [comment]
Please also read the documentation of this feature: https://github.com/akeeba/loginguard/wiki/U2F

There are pitfalls, e.g. that it won't be available if your site reports it is not running on HTTPS or if it running on HTTPS but on a self-signed certificate.

**Comment by sgofferj** [comment]
Oh, there was a plugin... My bad, I didn't look for plugins. In my defense - I did look for instructions on the Akeeba website, though. Apologies for the waste of time!

**Comment by nikosdion** [comment]
Only our paid extensions and Akeeba DataCompliance have their documentation on our site. Everything else is documented in the Wiki tabs of the respective GitHub repository. The README displayed when you open the GitHub repository links you to the documentation Wiki.

**Comment by sgofferj** [comment]
I will remember that! Thanks! On the bright side, I can report that it works fine in my configuration:
Joomla container <--> http <--> traefik --> https <--> client
Only "special" configuration is "force https=on" in the J! global config.

**Comment by nikosdion** [comment]
Yup, that's required for Joomla to know that it's running under HTTPS even though the web server reports otherwise :)

Have a great day!

**Comment by sgofferj** [comment]
Same to you!
