### ISSUE TITLE
[OTHER] How to disable a user's TFA

### ISSUE THREAD

**Issue by ManagerS-IT** [akeeba/loginguard#101]
A user is unable to log in using TFA, for example because he has lost his code.
There is a second user with SuperAdmin rights
How can this Super Admin disable the use of TFA for the other user?

**Comment by nikosdion** [comment]
Edit the user record, disable two step verification. 

Caveat: Super Users can't change other Super Users' settings. User B would have to first change user A to registered, save, edit user A, disable two step verification, save, make user A a Super User again.
