### ISSUE TITLE
Loginguard update 3.3.0 to 4.0.0: Class 'FOF30\Container\Container' not found. 

### ISSUE THREAD

**Issue by innertruth** [akeeba/loginguard#102]
Please read the README.md in the repository's root and the support resources before submitting an issue.

### Steps to reproduce the issue

Be specific. You may link to one or more screenshots or a video as long as it's not the only clue you leave. Use words to describe what happens.

First I updated all the extensions presented by the Joomla update process:
Admin Tools Pro, Akeeba Backup Pro, FEF, FOF 4.0. Then I noticed the github mentioning it couldn't access the Loginguard update URL. So I downloaded the latest Loginguard version to use it for updating.

After updating Loginguard 3.3.0 to Loginguard 4.0.0, I get:
 Class 'FOF30\Container\Container' not found. 

Site admin keeps giving this error whatsover I try to access in the admin.
In the webserver error log I see no errors about this.

Had to restore site from backup, updating everything again it happened again. I just wanted to be sure. Restored from backup again, updated extensions except Loginguard.

### Expected result

What you believed should have happened following the steps you outlined above.

Updating to Loginguard 4.0.0 performed succesfully without errors.

### Actual result

What actually happened.

After updating Loginguard 3.3.0 to Loginguard 4.0.0, I get:
 Class 'FOF30\Container\Container' not found. 
All links within the backend gives this error.

### Troubleshooting already performed

Please tell us about any troubleshooting you already performed and its results.

I read this: https://www.akeeba.com/news/1745-about-our-fof-and-fef-frameworks-and-their-future.html but could not relate the different fof/fef to Loginguard.

I read various "Class 'FOF30\Container\Container' not found." related support items on the Akeeba site looking for clues what to do, but not tried any as they seem related mostly to AdminTools and Backup.

#### Mandatory information

Issues without this information can not and _will not_ be replied to.

* **Joomla! version**: 3.9.25
* **PHP version**: 7.4.15
* **Am I using HTTPS**: Yes
* **Server Operating System**: Linux
* **My device's Operating System**: Windows and Linux
* **My device's Operating System version**: Windows 10 and Linux Mint 20.1
* **Browser**: Chrome
* **Browser version**: Version 89.0.4389.90 (Ofifcial build) (64-bits)

#### Good to have information

You can skip some or all of this information. However, the more information you provide the faster and better we can help.

* **MySQL version**: 5.5.5-10.4.17-MariaDB-log-cll-lve
* **Server type**: Apache, 
* **Server version**: 3.10.0-962.3.2.lve1.5.38.el6h.x86_6
* **Hosting company / Local server**: Antagonist
* **Server Operating System version**: Linux

### Additional comments

I apologize in advance if I have done something stupid in this updating process.

Cheers,

Gahan Zwart

**Comment by nikosdion** [comment]
Did you try https://www.akeeba.com/news/1744-advice-for-install-probs-with-march-2021-software-releases.html 

Note this is a different article than the one you linked to; it's actually the one published immediately before it.

**Comment by innertruth** [comment]
Oh guess I missed that one. Gonna look into that in the evening, hope I can 
resolve this for Loginguard.

Cheers,

Gahan Zwart
Op 28 maart 2021 14:48:18 schreef "Nicholas K. Dionysopoulos" 
***@***.***>:

**Comment by innertruth** [comment]
I have read the article, and looked if the fof30 was still present in the libraries dir, but it is/was still there. I did replace the fof30 files via ftp with the download mentioned in the article, just to try that, but still I get the same "Class 'FOF30\Container\Container' not found"

Going to restore from backup again, because the frontend also shows the same error.

**Comment by nikosdion** [comment]
If you have template overrides you will need to update them. Note that LoginGuard 3 was running on FOF 3, LoginGuard 4 runs on FOF 4. If your template overrides still reference FOF 3 they will break.

**Comment by innertruth** [comment]
This site was set up in 2017, but I had some notes on building this site. Alas I couldn't find something about a template override. I looked at the webserver error log again, maybe I missed something, but all I see is red herrings. Anything else I can look at? Or what info can I give more to give more insight in a probable cause?

**Comment by nikosdion** [comment]
Go to Global Configuration. Set Debug Site to Yes and Error Reporting to Maximum. Reproduce your issue. You should have a debug trace that tells you what is going on. At best it's a template override. At worst Joomla messed up the upgrade and there are old files left on your site.

**Comment by innertruth** [comment]
Okay done that, this is the trace. Not directly seeing something from a template, so I guess it's the worst scenario? If so, is there still something I can do?

Call stack
--
# | Function | Location
1 | () | JROOT/plugins/system/engagecache/engagecache.php:51
2 | plgSystemEngagecache->onAfterInitialise() | JROOT/libraries/joomla/event/event.php:70
3 | JEvent->update() | JROOT/libraries/joomla/event/dispatcher.php:160
4 | JEventDispatcher->trigger() | JROOT/libraries/src/Application/BaseApplication.php:108
5 | Joomla\CMS\Application\BaseApplication->triggerEvent() | JROOT/libraries/src/Application/CMSApplication.php:646
6 | Joomla\CMS\Application\CMSApplication->initialiseApp() | JROOT/libraries/src/Application/AdministratorApplication.php:301
7 | Joomla\CMS\Application\AdministratorApplication->initialiseApp() | JROOT/libraries/src/Application/AdministratorApplication.php:123
8 | Joomla\CMS\Application\AdministratorApplication->doExecute() | JROOT/libraries/src/Application/CMSApplication.php:203
9 | Joomla\CMS\Application\CMSApplication->execute() | JROOT/administrator/index.php:51

**Comment by nikosdion** [comment]
Please remember to also upgrade Akeeba Engage which appears to be installed on your site.

**Comment by innertruth** [comment]
Ah so that is what the engagecache refers to! I think I installed it once upon a time, and then removed it later. Because I don't see it within the Components and I never see it in the updates. Guess some files have been left behind. Okay restoring from backup again and ill try to investigate.

**Comment by nikosdion** [comment]
Please do remember that when you install a package type extension you are supposed to uninstall the package type extension, not just the component. Otherwise you ARE leaving behind plugins, modules, library extensions, file extensions etc which quickly become out of date and can cause issues on your site.

I am closing this as "user shot his own two feet"... er... I mean "invalid" 😉

**Comment by innertruth** [comment]
I am closing this as "user shot his own two feet"... er... I mean "invalid" wink

Damn... you are right! So much for me being (trying to be)  a good web maintainer... ...sigh...  

Thank you!

**Comment by nikosdion** [comment]
It happens to everyone!

Remember that I am a developer and I am fixing my own bugs which makes both the detective and the murdered in my own murder mystery dinner every single day...

**Comment by innertruth** [comment]
Actually turns out Engage was still complete, but I couldn't see that till after the restore. So I uninstalled the package type, updated loginguard from 3.3.0 tot 4.0 and the world is perfect again. Thanks again getting me on the right track. I guess I didn't shoot my two feet, I was just blind. wink

**Comment by nikosdion** [comment]
No problem! Have a great evening :)
