### ISSUE TITLE
Change verification isn't working

### ISSUE THREAD

**Issue by tgermain-da** [akeeba/loginguard#104]
We have enabled email and authenticator app. If a new user gets prompted for MFA, they can choose either method and it works. 

The user chooses email and logs in successfully.
They log out.
They log back in.
They click the link to choose another authentication method.
Only email and codes show up, but the authenticator option isn't presented to them.

**Comment by nikosdion** [comment]
Please read the documentation: https://github.com/akeeba/loginguard/wiki/The-component-Options#the-remember-me-options 

It sounds like you simply want to disable the Remember Me option.
