### ISSUE TITLE
Error 403 when resetting backup codes

### ISSUE THREAD

**Issue by WimVDK** [akeeba/loginguard#106]
Please read the README.md in the repository's root and the support resources before submitting an issue.

### Steps to reproduce the issue

- Install joomla fresh
- install loginguard
- add authenticator app
- click to access the backup codes
- immediately "accidentally" click to 'Regenerate Backup codes"

### Expected result

Backup codes getting changed

### Actual result

Error 403 Forbidden

### Troubleshooting already performed

Other than installing a few times over the top, don't know what else to try.

#### Mandatory information

Issues without this information can not and _will not_ be replied to.

* **Joomla! version**: 3.9.26
* **PHP version**: 7.4.18
* **Am I using HTTPS**: Yes
* **Server Operating System**: Linux
* **My device's Operating System**: Windows
* **My device's Operating System version**: Win 10 Pro 20H2 x64
* **Browser**: Firefox
* **Browser version**: 88.0.1

#### Good to have information

You can skip some or all of this information. However, the more information you provide the faster and better we can help.

* **MySQL version**:  5.5.5-10.2.38-MariaDB 
* **Server type**: Apache
* **Server version**: Linux 7.9.2009
* **Hosting company / Local server**: self-hosting
* **Server Operating System version**: CentOS

**Comment by nikosdion** [comment]
I am already working on a successor version using Joomla! core MVC. Can you please try it and tell me if that fixes this problem? A developer's release is attached below.

[pkg_loginguard-rev43B0106.zip](https://github.com/akeeba/loginguard/files/6460740/pkg_loginguard-rev43B0106.zip)

**Comment by WimVDK** [comment]
Installed fine, No error 403 on clicking regenerate, but the codes don't change. Yellow warning box is displayed "The security token doesn't match. Request aborted to prevent a breach on security. Try again"

**Comment by nikosdion** [comment]
Thank you for testing! I found where the problem was. I had fixed that for regular Two Step Verification methods but I forgot to address it for the Backup Codes which are handled a bit differently. Please try installing the new dev release attached below.

Thank you in advance for your feedback!

[pkg_loginguard-rev3694B18.zip](https://github.com/akeeba/loginguard/files/6464492/pkg_loginguard-rev3694B18.zip)

**Comment by WimVDK** [comment]
Installed fine, no issues. Went to manage 2FA, accessed backup codes. Fix confirmed. regenerated multiple times with zero issues. Changed everytime, no warnings, nothing. Just code changes :)

**Comment by nikosdion** [comment]
Thank you very much for the feedback!
