### ISSUE TITLE
Akeeba LoginGuard - An unhandled Exception has been detected

### ISSUE THREAD

**Issue by johanpeters** [akeeba/loginguard#110]
Please read the README.md in the repository's root and the support resources before submitting an issue.

### Steps to reproduce the issue

after joomla update to 3.10.0 after login i get this error.
also after login in backend and open loginguard settings this error

### Expected result

available of loginguard MFA login page. (not forced)

### Actual result

after login display of error.

### Troubleshooting already performed

check latest version. remove and reinstall version 5.0.1
#### Mandatory information

Issues without this information can not and _will not_ be replied to.

* **Joomla! version**: 3.10.0
* **PHP version**: 7.4
* **Am I using HTTPS**: Yes
* **Server Operating System**: Linux
* **My device's Operating System**: Windows,.
* **My device's Operating System version**: windows 10
* **Browser**: Chrome, v92

**Comment by nikosdion** [comment]
Yes, I am aware. Joomla 3.10.0 introduced a backwards incompatible change AFTER its last release candidate. Joomla screwing something up on release day? Ah, it must be a day ending in -y.

**Comment by nikosdion** [comment]
Fixed in version 5.0.2 released a few minutes ago.
