### ISSUE TITLE
J4 pre-update checker triggered an unhandled exception

### ISSUE THREAD

**Issue by WimVDK** [akeeba/loginguard#112]
### Steps to reproduce the issue

With the release of J4 i had a look at the upgrade instructions. I visited https://docs.joomla.org/Joomla_3.x_to_4.x_Step_by_Step_Migration and applied the steps upto point 6 under "assess each extension". Point 6 is `Look at the Pre-Update Check and the Extension Pre-Update Check in the Pre-Update Check tab of the Joomla Update component. If any extension that isn’t in your planning is listed here, add it to your list of extensions to investigate.`

I stopped there as there was an rsjoomla that showed possible incompatibility (so i'm waiting on an update for that). Closed the browser tab. Just now (around 2hrs later i logged back in). Initial login with username & password worked fine, the phase where it checks for the trusted fingerprint is where it went wrong i think.

### Expected result

Succesful login

### Actual result

![afbeelding](https://user-images.githubusercontent.com/14872315/129777838-02a2a91c-50c8-44a0-ab9f-591219c6dfdf.png)

While the frontend remained operational, the backend did not. The menu was fully operational, just no matter what i clicked on, only that error was displayed. As the image shows, i did NOT upgrade to 4.0. I merely followed the steps to check for any extension compatibility issues according to the instructions.

### Troubleshooting already performed

Going into the database table __extensions, and changing enabled from 1 to 0 for "com_loginguard" (yes i know from a previous response in a different issue, regarding assets etc, that this is not advised. My limited knowledge in that regard does know that all changing that single field from "enabled" to "disabled" does, is prevent joomla from loading it. Doesn't actually remove any folders or installation references anywhere. But please correct me if i'm wrong!)
and refreshing the page resulted initially in Error 404 page not found (logical, since joomla was trying to pull a view for a component that is now disabled. I'm guessing it was going to ask me for a 2FA code). With the loginguard component now disabled, clicking on whatever option in the menu properly pulled up the corresponding extension/view.

My guess, between release 5.0.1 and J3.10.0 / J4 they did a some kind of last minute change that broke loginguard's 2FA code asking view entirely.

#### Mandatory information

Issues without this information can not and _will not_ be replied to.

![afbeelding](https://user-images.githubusercontent.com/14872315/129776760-234beb72-820b-4965-84b5-8697df0289e5.png)

**Comment by johanpeters** [comment]
Update loginguard to 5.02
This will fix this issue

Op 17 aug. 2021 20:06, om 20:06, Ch3vr0n ***@***.***> schreef:

**Comment by WimVDK** [comment]
That'll be a task for tomorrow then, odd though. Extension updater didn't tell me about 502. On Aug 17, 2021 20:41, johanpeters ***@***.***> wrote:

Update loginguard to 5.02

This will fix this issue



Op 17 aug. 2021 20:06, om 20:06, Ch3vr0n ***@***.***> schreef:

**Comment by WimVDK** [comment]
Confirmed, problem solved.
