### ISSUE TITLE
#115 has not been solved in 5.0.4 ??

### ISSUE THREAD

**Issue by rbuelund** [akeeba/loginguard#116]
You have closed #115 and refered to the solving of #114 - but version 5.0.4 has not solved the problem in #115 ???

**Comment by nikosdion** [comment]
Oh for crying out loud, this is the **SIXTH** notification email I receive from you within an hour! I am maintaining this software for free, in my spare time. I am not your employee, let alone your slave. I will get to it when I get to it. Stop pestering me!
