### ISSUE TITLE
Picking specific joomla template for loginguard component

### ISSUE THREAD

**Issue by joomlafun** [akeeba/loginguard#118]
Hi,

Thanks for this great plugin and for providing it for free, they should bring email tsv auth by default with joomla.

May I ask how to use another template than my default joomla template with the "captive view" please.(I use 2 templates for my site)?

Kind regards,

**Comment by nikosdion** [comment]
There was no way to do that. I implemented a new feature. There will be a new release next week which will include it.

The new feature is in the component's Options. You can select any template style defined on your site. It will be used for the frontend captive login pages.

**Comment by joomlafun** [comment]
Thank you for taking the time to implement this.
