### ISSUE TITLE
email tsv auth code sent twice from time to time

### ISSUE THREAD

**Issue by joomlafun** [akeeba/loginguard#119]
Hi,

From time to time the email with the verification code gets sent twice with the same code for the 2 emails.
I'm on Joomla 3.10.3, php 7.4.25 , I use the default php mail feature of joomla

![githubsenttwice](https://user-images.githubusercontent.com/63743077/141296470-e2c8413d-e404-4d48-bbc2-578a07196273.png)
![Screenshot_20211111_112222](https://user-images.githubusercontent.com/63743077/141296054-d5e1386f-e321-46ef-9d4b-87be06cffe29.png)

**Comment by nikosdion** [comment]
No, it is not sent twice. Your browser is accessing the page twice, each page load sends the code once as it should.

If you were to see the seconds in the email timestamps you'd see that I'm right. The emails are not sent at the same time, they are sent a few seconds apart.

You know how browsers auto–complete the URL? They don't just auto–complete the URL, they access the URL as well in the background. Each time they do that it counts as a page load and the email is sent to you. 

Also, remember what we discussed last week about how Remember Me works? If you see the Remember Me page an email is sent. Then you see the page to enter the code, another email is sent.

**Comment by nikosdion** [comment]
It's the same case from a code perspective. Let's not open a million issues about the same thing, it actually makes it far more difficult to keep track.

**Comment by nikosdion** [comment]
I have made a change which will address the double code sending. It will be included in a new version to be released next week.

**Comment by joomlafun** [comment]
Thank you for solving this.
