### ISSUE TITLE
An unhandled Exception has been detected during 2FA Migration

### ISSUE THREAD

**Issue by SpyderZ** [akeeba/loginguard#120]
Installed version 5.0.7 on Joomla 4.1 and got this error when trying to migrate away from the core 2FA to LoginGuard.

Centos 7.9
PHP 8.0.15
MariaDB 10.4.24

Akeeba LoginGuard - An unhandled Exception has been detected
500 Failed opening required '/var/www/vhosts/domain.com/httpdocs/libraries/fof/include.php' (include_path='.:/opt/plesk/php/8.0/share/pear')
File &lt;root&gt;/administrator/components/com_loginguard/models/convert.php Line 382

 The content below this point is for developers and power users.

Joomla 4.1.0 – PHP 8.0.15 on Linux

Debug information
Exception type: Error

#0 /var/www/vhosts/domain.com/httpdocs/administrator/components/com_loginguard/models/convert.php(335): LoginGuardModelConvert->decryptTFAStringJoomla3()
#1 /var/www/vhosts/domain.com/httpdocs/administrator/components/com_loginguard/models/convert.php(69): LoginGuardModelConvert->decryptTFAString()
#2 /var/www/vhosts/domain.com/httpdocs/administrator/components/com_loginguard/controllers/convert.php(35): LoginGuardModelConvert->convert()
#3 /var/www/vhosts/domain.com/httpdocs/libraries/src/MVC/Controller/BaseController.php(735): LoginGuardControllerConvert->convert()
#4 /var/www/vhosts/domain.com/httpdocs/administrator/components/com_loginguard/loginguard.php(80): Joomla\CMS\MVC\Controller\BaseController->execute()
#5 /var/www/vhosts/domain.com/httpdocs/libraries/src/Dispatcher/LegacyComponentDispatcher.php(69): require_once('...')
#6 /var/www/vhosts/domain.com/httpdocs/libraries/src/Dispatcher/LegacyComponentDispatcher.php(71): Joomla\CMS\Dispatcher\LegacyComponentDispatcher::Joomla\CMS\Dispatcher\{closure}()
#7 /var/www/vhosts/domain.com/httpdocs/libraries/src/Component/ComponentHelper.php(389): Joomla\CMS\Dispatcher\LegacyComponentDispatcher->dispatch()
#8 /var/www/vhosts/domain.com/httpdocs/libraries/src/Application/AdministratorApplication.php(143): Joomla\CMS\Component\ComponentHelper::renderComponent()
#9 /var/www/vhosts/domain.com/httpdocs/libraries/src/Application/AdministratorApplication.php(186): Joomla\CMS\Application\AdministratorApplication->dispatch()
#10 /var/www/vhosts/domain.com/httpdocs/libraries/src/Application/CMSApplication.php(278): Joomla\CMS\Application\AdministratorApplication->doExecute()
#11 /var/www/vhosts/domain.com/httpdocs/administrator/includes/app.php(63): Joomla\CMS\Application\CMSApplication->execute()
#12 /var/www/vhosts/domain.com/httpdocs/administrator/index.php(32): require_once('...')
#13 {main}

**Comment by nikosdion** [comment]
I don't think you installed LoginGuard on Magento, more like Joomla.

No, import does not work on Joomla 4 with LoginGuard 5. I am not even sure if this feature will be ported to the Joomla 4 only version 6 or just get removed.

**Comment by SpyderZ** [comment]
> I don't think you installed LoginGuard on Magento, more like Joomla.
> 
> No, import does not work on Joomla 4 with LoginGuard 5. I am not even sure if this feature will be ported to the Joomla 4 only version 6 or just get removed.

Ha, sorry, I've been all over in different systems today, and they're both the same version. I went and disabled 2-FA from Joomla and then enabled it with LoginGuard and it works fine now.

**Comment by nikosdion** [comment]
I cleaned up the code and remove the Joomla 3 stuff from it. LoginGuard 6 should be able to do an import from core 2FA just fine. I expect us to release it in early April.
