### ISSUE TITLE
not getting captive for yubikey on joomla 4 after upgrade from joomla 3.

### ISSUE THREAD

**Issue by innertruth** [akeeba/loginguard#129]
Please read the README.md in the repository's root and the support resources before submitting an issue.

### Steps to reproduce the issue

Log in to backend Joomla 4, install Loginguard, set Yubikey up for superuser (is only user on system) with no errors/warnings, log out, log in, but after logging in with user/pw I get no captive screen asking for yubikey code.

### Expected result

Get captive asking for yubikey code after login

### Actual result

I have a site that has been upgraded from 3.10 to Joomla 4 a month ago, which had Loginguard working fine asking for the yubikey code everytime in Joomla 3.x. But after the upgrade that doesn't work anymore. Deinstalled and reinstalled Loginguard new versions several times, but still no dice, After normal login I get no captive screen for yubikey code.

### Troubleshooting already performed

Everytime I install it Loginguard says it's working properly. All other J 3.x websites I have work fine with the yubikey. I get no errors or warnings. I have also tried deleting all cookies for this site, disabling caching in Joomla. I also enabled logging on the site to maximum and in Session I see this, but do not know the meaning:

com_loginguard
array:5 [
  "browserId" => null
  "browserIdCodeLoaded" => false
  "return_url" => "https://[www.site.toplevel]/administrator/index.php"
  "imperfect_return" => true
  "captiveUrl" => "/administrator/index.php?option=com_loginguard&view=captive"
]

#### Mandatory information

Issues without this information can not and _will not_ be replied to.

* **Joomla! version**: 4.1.2
* **PHP version**: 8.0.17
* **Am I using HTTPS**: Yes
* **Server Operating System**: Linux
* **My device's Operating System**: Linux, Windows
* **My device's Operating System version**: Linux Mint 20.3, Windows 10 Home Ed.
* **Browser**: Google Chrome on Linux, Brave on Windows 10
* **Browser version**: Google Chrome Version 100.0.4896.60 (Official build) (64-bits), Brave idk

#### Good to have information

You can skip some or all of this information. However, the more information you provide the faster and better we can help.

* **MySQL version**: mariadb 10.4.22-MariaDB-log-cll-lve
* **Server type**: Apache
* **Server version**: idk, probably 2.4
* **Hosting company / Local server**: antagonist.nl
* **Server Operating System version**: Cloudlinux 1.3, kernel 4.18.0-305.17.1.lve.el8.x86_64 #1

### Additional comments
I use a yubikey 4
I also user Admin Tools and Akeeba backup
I also have .htaccess implemented via Admin Tools.

Cheers, Gahan Zwart

**Comment by nikosdion** [comment]
Cannot reproduce. Note that your server config as described is identical to one of the two development servers I am using.

Make sure you are NOT using the Remember Me feature: https://github.com/akeeba/loginguard/wiki/The-component-Options#the-remember-me-options

Make sure you have enabled Two Step Verification on your user account. Uninstalling the component will **remove** your previous setup.

Make sure BOTH the system AND the user plugin are published with their Access set to **Public** per the documentation.

Make sure you have not messed with the forced allowed / disallowed two step verification per user group (https://github.com/akeeba/loginguard/wiki/The-component-Options#control-who-sees-two-step-verification).

Make sure that “YubiKey” refers to the Yubikey OTP code, NOT U2F (U2F support has been removed per the release notes).

**Comment by innertruth** [comment]
Hi,

Checked everything like you said, but everything is like you said. I have not fiddled with any settings. So I tried some things. I noticed it is a problem after adding a yubikey. I added my backup yubikey which itself had no problem, but after I did Save & Close I got this:

Er heeft zich een fout voorgedaan.

	0 Joomla\CMS\User\UserFactory::loadUserById(): Argument #1 ($id) must be of type int, null given, called in [yadayadayada]/public_html/plugins/user/loginguard/src/Extension/LoginGuard.php](http://cmsjoy.nl/public_html/plugins/user/loginguard/src/Extension/LoginGuard.php) on line 170

Call stack
#
Function
Location
1
()
JROOT/libraries/src/User/[UserFactory.ph](http://userfactory.ph/)p:48
2
Joomla\CMS\User\UserFactory->loadUserById()
JROOT/plugins/user/loginguard/src/Extension/[LoginGuard.ph](http://loginguard.ph/)p:170
3
Joomla\Plugin\User\Loginguard\Extension\LoginGuard->onContentPrepareForm()
JROOT/libraries/vendor/joomla/event/src/[Dispatcher.ph](http://dispatcher.ph/)p:486
4
Joomla\Event\Dispatcher->dispatch()
JROOT/libraries/src/Application/[EventAware.ph](http://eventaware.ph/)p:111
5
Joomla\CMS\Application\WebApplication->triggerEvent()
JROOT/libraries/src/MVC/Model/[FormBehaviorTrait.ph](http://formbehaviortrait.ph/)p:179
6
Joomla\CMS\MVC\Model\FormModel->preprocessForm()
JROOT/administrator/components/com_users/src/Model/[UserModel.ph](http://usermodel.ph/)p:216
7
Joomla\Component\Users\Administrator\Model\UserModel->preprocessForm()
JROOT/libraries/src/MVC/Model/[FormBehaviorTrait.ph](http://formbehaviortrait.ph/)p:117
8
Joomla\CMS\MVC\Model\FormModel->loadForm()
JROOT/administrator/components/com_users/src/Model/[UserModel.ph](http://usermodel.ph/)p:126
9
Joomla\Component\Users\Administrator\Model\UserModel->getForm()
JROOT/libraries/src/MVC/Controller/[FormController.ph](http://formcontroller.ph/)p:629
10
Joomla\CMS\MVC\Controller\FormController->save()
JROOT/administrator/components/com_users/src/Controller/[UserController.ph](http://usercontroller.ph/)p:106
11
Joomla\Component\Users\Administrator\Controller\UserController->save()
JROOT/libraries/src/MVC/Controller/[BaseController.ph](http://basecontroller.ph/)p:735
12
Joomla\CMS\MVC\Controller\BaseController->execute()
JROOT/libraries/src/Dispatcher/[ComponentDispatcher.ph](http://componentdispatcher.ph/)p:146
13
Joomla\CMS\Dispatcher\ComponentDispatcher->dispatch()
JROOT/libraries/src/Component/[ComponentHelper.ph](http://componenthelper.ph/)p:389
14
Joomla\CMS\Component\ComponentHelper::renderComponent()
JROOT/libraries/src/Application/[AdministratorApplication.ph](http://administratorapplication.ph/)p:143
15
Joomla\CMS\Application\AdministratorApplication->dispatch()
JROOT/libraries/src/Application/[AdministratorApplication.ph](http://administratorapplication.ph/)p:186
16
Joomla\CMS\Application\AdministratorApplication->doExecute()
JROOT/libraries/src/Application/[CMSApplication.ph](http://cmsapplication.ph/)p:278
17
Joomla\CMS\Application\CMSApplication->execute()
JROOT/administrator/includes/[app.ph](http://app.ph/)p:63
18
require_once()
JROOT/administrator/[index.ph](http://index.ph/)p:32

Please advise.

Cheers,

Gahan Zwart

**Comment by nikosdion** [comment]
Please upgrade to LoginGuard 6.0.3. This issue is already fixed there.
