### ISSUE TITLE
Block of raw ajax request

### ISSUE THREAD

**Issue by rbuelund** [akeeba/loginguard#131]
Please read the README.md in the repository's root and the support resources before submitting an issue.

### Steps to reproduce the issue

Install version 3.7.1 of jRealtime Analytics that is making raw ajax request.

### Expected result

Loginflow should work as expected

### Actual result

The raw ajax request from jRealtime Analytics is blocked by Loginguard and breaks the loginflow

### Troubleshooting already performed
The developer of jRealtime Analytics is writng this answer:
"I've found the reason to the issue with akeeba loginguard.

The problem is that on the second step verification page he's also blocking raw ajax requests with a 307 redirect to the same page.

I've added an exclusion in JRealtime and the problem is solved for this component.

But the developer of akeeba should change the component to avoid to redirect raw ajax requests. Otherwise whatever component doing this will break the 2SV login."

### System information
Joomla 3.10
Akeeba Loginguard 5.0.7
jRealtime Analytics 3.7.1

**Comment by nikosdion** [comment]
I discovered that while contributing LoginGuard's code to Joomla itself. What I did there is block these non-HTML requests with a 403. Please check with the developer that a 403 is handled gracefully as it should.

This code will be included in Joomla 4.2 or, at worst, 4.3. At this point LoginGuard will be discontinued. So it's in his best interest to support this kind of multi factor authentication before Joomla 4.2/4.3 is released. 

Finally, I'd like to note that I am no longer developing the Joomla 3 version of LoginGuard. We're just one year and 3 months away from Joomla 3 becoming end of life. At this point in time any J3 site which does not already have an imminent migration plan to Joomla 4 is a dead site, there's no incentive for me to keep supporting these sites with free of charge software.

**Comment by rbuelund** [comment]
Thank you for the answer. So the plan is that the loginguard logic is gonna be included in Joomla core ?
I am aware, and have planned to migrate the site to Joomla 4 - but it all takes time - and some extensions are not yet ready - but almost there :-)
