### ISSUE TITLE
truncated placeholders

### ISSUE THREAD

**Issue by PhilETaylor** [akeeba/loginguard#21]
url: http://example.com/administrator/index.php?option=com_config&view=component&component=com_loginguard&path=&return=aHR0cDovL3JlbW90ZWJmYi9hZG1pbmlzdHJhdG9yL2luZGV4LnBocD9vcHRpb249Y29tX2xvZ2luZ3VhcmQmdmlldz13ZWxjb21l

<img width="477" alt="screen shot 2017-03-12 at 17 53 46" src="https://cloud.githubusercontent.com/assets/400092/23834336/e5ac72b4-074c-11e7-85e8-c9c1c5285d12.png">

**Comment by nikosdion** [comment]
This page is rendered by com_config which is part of Joomla!. I have NOT written com_config, I have NOT written Joomla's select field, I have NOT written chosen.js, I can NOT debug Joomla's broken crap.

**Comment by nikosdion** [comment]
BTW, this doesn't happen in 3.6.5 so I guess you found yet another Joomla! 3.7 bug.

**Comment by PhilETaylor** [comment]
`<input type="text" value="Type or select some options" class="default" autocomplete="off" style="width: 90px;">`

Its the 90px width thats killing it I think... Im no frontend guru though
