### ISSUE TITLE
Missing Itemid

### ISSUE THREAD

**Issue by nikosdion** [akeeba/loginguard#31]
Received the following bug report:

> I integrated the LoginGuard in our site but I face a problem with a missíng Itemid. When I regenreate Backup Codes at option=com_loginguard&Itemid=196&task=method.edit the Itemid=196 gets lost. It is also lost when I enter the wrong six digit code while setting up the authenticator app.

This points to the redirection URL being wrong when setting up / editing a method in the frontend.

**Comment by nikosdion** [comment]
Can not reproduce. The URLs are stored correctly by both the system plugin and LoginGuardControllerMethod.

**Comment by helgator** [comment]
I can still reproduce it at component/loginguard/?task=method.edit&user_id=978&id=6&returnurl=... see, no Itemid when you click on the button to regenerate the backup codes. Would you like to have access to my site?

**Comment by nikosdion** [comment]
There should be no Itemid in that URL (and correctly there is none). That's because you don't have a menu item pointing to that page which is exactly how it's supposed to work - JRoute will not add an arbitrary Itemid.

The Itemid is only important in the redirect, i.e. the URL you end up _after_ setting up / modifying two factor authentication. This URL is base64-encoded in the returnurl parameter. I have confirmed that the returnurl parameter does keep the Itemid as it's supposed to do.

Therefore there is no bug there.

**Comment by helgator** [comment]
True, there is no menu item pointing. That is why it needs to inherrit that Itemid from the URL of the page the "Generate Backup Codes"-button is placed on: component/loginguard/?Itemid=196&task=method.edit&id=6&returnurl=.... If the Itemid is not kept how does the system know which modules to display on that page when it returns the new backup codes?

**Comment by nikosdion** [comment]
LoginGuard is supposed to not have a menu item in the front-end (since everything has to be rendered inside the com_users system component through plugins). Therefore only modules assigned to All Pages will be shown. Using an Itemid is **the wrong approach**. The Itemid DOES NOT simply define which modules are loaded but also which component, view, task, layout and format are being rendered AND which front-end router (router.php) is supposed to parse the URL. Since LoginGuard only sets a component and task parameter it's possible that conflicting content in the menu item defined by an Itemid would break it.

Sorry, this is how Joomla! works. I don't like it either.
