### ISSUE TITLE
Option to user Mobile Number to send code

### ISSUE THREAD

**Issue by frogydiak** [akeeba/loginguard#32]
It would be awesome and much more easier for end user if there is an option to send code to Mobile Number. 

Google 2FA is a pain to use and a user has to be technically inclined.

**Comment by nikosdion** [comment]
Duplicate of https://github.com/akeeba/loginguard/issues/8 which is already implemented [and documented](https://github.com/akeeba/loginguard/wiki/SMSAPI) since April.
