### ISSUE TITLE
 Upgrade the GeoIP database failed

### ISSUE THREAD

**Issue by blueforce** [akeeba/loginguard#35]
### Steps to reproduce the issue
1. go to  components -> login guard: ROOT/administrator/index.php?option=com_loginguard&view=welcome
2. Klick the "Upgrade the GeoIP database"-Button
3. The Failure appears 404 view not found

Make sure your issue can be reproduced on a new installation of Joomla! without any modified configuration settings or third party extensions. If the issue only occurs with a specific third party extension or configuration setting please specify exactly what triggers it. Always keep in mind that if it can't be reproduced it can't be fixed!

### Expected result
Update the Geo-DB

### Actual result
404 View nicht gefunden [Name, Typ, Präfix]: loginguard, html, loginguardView

### System information (as much as possible)
* **Joomla! version**: 3.7.5
* **Database type**: MySQL
* **Database version**: 5.6.33-cll-lve
* **Server type**: LiteSpeed, 
* **Server version**: Version 5.2.1 (Stable)
* **Hosting company / Local server**: cyon.ch
* **Am I using HTTPS**: Yes
* **Server Operating System**: Linux,
* **Server Operating System version**: N/A if it's a live host and you have no idea. 
* **Browser**: Chrome, Firefox, Edge, Internet Explorer, Safari, Opera, ...
* **Browser version**: x.y.z

### Additional comments
Tested with the actual Loginguard 1.2 Version

**Comment by nikosdion** [comment]
Cannot reproduce. I suspect that Joomla! forgot to copy files on extension update (again!). Please try to install the component twice in a row, **without** uninstalling it before or in between. Then retry upgrading the GeoIP database. Did that work for you?

**Comment by blueforce** [comment]
where is the needed file located?

path:
administrator/components/com_loginguard/views/welcome/tmpl/default.php ?

**Comment by nikosdion** [comment]
I do not understand your question. The file is in the path you mentioned. It's tautology. What exactly do you want me to help you with?

**Comment by nikosdion** [comment]
Closing issue after long period of inactivity.
