### ISSUE TITLE
Support U2F Key

### ISSUE THREAD

**Issue by Techal62** [akeeba/loginguard#40]
Hello, on the new version, do you still support U2F compatible keys, when I install the module on Joomla 3.8.
I have a page that only offers Yubikey or Application Authentication.
Thank you

**Comment by Techal62** [comment]
But when I want to print emergency security code it's my mark page not found; the link ends with https: // *** / administrator / _QQ_

**Comment by nikosdion** [comment]
U2F is of course supported... by the U2F plugin. Which I use on all of my sites.
