### ISSUE TITLE
Exclude on X usergroups?

### ISSUE THREAD

**Issue by tonypartridge** [akeeba/loginguard#43]
Hi Nicholas,

I am just wondering what your thoughts are on adding a config option to the plugin to not run on X user groups? 

For example, we have a scenario where we have 2,500 user groups we want around 100 of them not to be effected by TFA since it's not relevant for their usage case. 

I was thinking a single usergroup selector in the Plugin and all users groups within this selection are excluded from requiring FTA?

Loving the component!

**Comment by nikosdion** [comment]
What’s wrong with using Joomla’s built in features which make this possible already?!

Create a new viewing level which includes the groups you want to make Two Step Verification available to. Edit both the system and the user plugin and assign them to that user level.

Do not try to reproduce core functionality that’s there for nine years ;)

**Comment by tonypartridge** [comment]
Hey Nicholas,

And a great idea that is... is an inclusion rule rather than an exclusion. So the site admins would need o remember every time hey create a new user group to apply it to the access level? Which is very unlikely they would and having an exclusion list of user groups would make sure the plugin runs always unless explicitly set not too :-).

**Comment by nikosdion** [comment]
To be clear: this. Is. Not. Going. To. Be. Implemented. 

We had that discussion in 2012 with the core two factor authentication. I am not having that discussion again. 

Two step verification and two factor authentication DO NOT protect your site, they protect your users from phishing. You are not their mother. Let them decide if they want this feature. If they don’t they can click on "don’t show this again" and that’s the end of it. If one of the methods is expensive for you to run (SMS for example) use the view levels to restrict its plugin to specific people.
