### ISSUE TITLE
[enhancement] allow to delete and not use backup codes

### ISSUE THREAD

**Issue by Aditza2015** [akeeba/loginguard#44]
Please allow us to delete and NOT use any backup codes if at least two other 2FA methods or devices are configured.

### Expected result
Administrators are allowed to delete any existing backup codes and not use them at all when there are already two or more other 2FA methods enabled. (in my case, i have multiple U2F keys and YK4 OTP keys).
When the backup codes are not active, if the deletion of a 2FA method would result in less than two methods remaining active after the removal then do not allow the deletion of 2FA methods.

### Actual result
backup codes are mandatory and are generated automatically even if i don't want them.
LoginGuard won't let me delete the backup codes that were generated and won't let me prevent the creation of new ones.

### System information (as much as possible)
* **Joomla! version**: 3.8.7
* **LoginGuard version**: 2.0.1
(i don't think the other info is needed)

**Comment by nikosdion** [comment]
This is never going to happen. Emergency backup codes are exactly that. To be used in an emergency. When you don't have access to your other methods. Removing them is like removing the seatbelts of a car. Sure, the car runs fine but if you get into a minor accident you die.

**Comment by Aditza2015** [comment]
i have a separate U2F security key that i keep for such emergencies.

for emergency purposes, what would be the difference between a sheet with printed codes stored in an envelope and a backup registered U2F key stored in the same envelope?

**Comment by Aditza2015** [comment]
p.s. the "never going to happen" bit is already happening with Google Accounts: if you choose to enable the advanced protection mode then it will disable the backup codes and POP3/IMAP email access. U2F becomes mandatory if you enable this for a Google Account:
https://landing.google.com/advancedprotection/

**Comment by nikosdion** [comment]
This is never going to happen. Which part of that phrase is so hard for you to understand?

**Comment by nikosdion** [comment]
P.S. In case it's not clear, I am not Google. So, no, what Google or whoever is doing or not doing is not going to change what I am willing to put my own time into implementing into my own open source software. I am not interested in your feature request, I have philosophical reasons I am opposing it and I was very upfront about it. If you are so desperate for me to implement feel free to pay me 100 Euros per hour + VAT to implement it for you - I'm afraid I don't have time though. Or fork the code and do it yourself. Or find someone else to do it for you. Just complaining about it to the person who told you *upfront* that this is never going to happen is beyond rude. My software is free, my time is not. If you cannot respect my time I'm not going to respect you. Issue locked.
