### ISSUE TITLE
LoginGuard v2.0.1 bug: only the first U2F Security Key is recognized for login

### ISSUE THREAD

**Issue by Aditza2015** [akeeba/loginguard#45]
### Steps to reproduce the issue
* install Joomla (v3.7.8 in my case, current one)
* install LoginGuard v2.0.1
* register multiple U2F Security Keys (or Yubikey4 keys in U2F mode) for 2FA login, for a single account. Give each key an unique name in the key configuration so that you can easily identify them in the list of keys on-screen. (i wrote numbers on the key plastic housing and i use that as visual guide)
* make sure "Authenticate with any configured security key" is enabled in the Joomla plugin configuration for Plugins: LoginGuard - Security Key (U2F)

### Expected result
i can login with any of the already-registered U2F Security Keys for that account.

### Actual result
i can login only with the first U2F Security Key that i registered, the other keys are not recognized even if i mark them as being the default key via the user configuration. 
If i try to login with the secondary keys i get the message: Error
Two Step Verification failed. Please try again.
I tested all keys and they are working correctly with this browser on https://demo.yubico.com/u2f

### System information 
* **Joomla! version**: 3.7.8
* **Database type**: MySQL
* **Am I using HTTPS**: Yes
* **Browser**: Firefox
* **Browser version**: 52.7.3 ESR with U2F support addon
(will also test Firefox 59 and Chrome later, when i go home)

**Comment by Aditza2015** [comment]
update: tested on Google Chrome, multiple U2F keys work here, seems it's only on Firefox ESR that this U2F behaviour happens.
I will close the issue since Firefox ESR 52 won't be around much longer: support for this ESR line is ending in August 2018.

**Comment by nikosdion** [comment]
Firefox' support for U2F is still mostly experimental and not finalized. While the FIDO U2F standard allows sending multiple registrations (key profiles) to the browser it's very likely that Firefox only honors one of them. There are also disparities in the way Firefox and Chrome may understand the domain name which is part of the U2F authentication. I've seen at least one (local) site where all keys work on Chrome but none works on Firefox.

At this point in time U2F only works reliably on Chrome and Opera as tested on all three major OS (Windows, Linux and macOS) with the latest versions of each browser installed. Firefox is hit-and-miss. I recommend using regular YubiKey support or another method as a backup in case you need to use Firefox and it gives you grief.
