### ISSUE TITLE
regenerate Backup Codes: Access Denied error

### ISSUE THREAD

**Issue by johanpeters** [akeeba/loginguard#47]
When i try to regenerate backup keys (normal user frontend, Super user backend). 
i receive a access denied.. no backup keys are generated..

**Comment by nikosdion** [comment]
This issue cannot be reproduced. Please make sure that you have not created a menu item for LoginGuard with Access set to something that excludes your user. Basically, your problem is using Joomla!, not our software. We can't provide generic Joomla! support. Sorry.
