### ISSUE TITLE
Forced 2SV for specific user groups

### ISSUE THREAD

**Issue by nikosdion** [akeeba/loginguard#49]
## Overview

Make 2SV mandatory for specific user groups (or everyone).

If a user logs in but they have not enabled 2SV we redirect them to the LoginGuard page (override the admin's custom redirection and the user's "don't show this again" flag). The login is now captive to the LoginGuard component until the user either enables 2SV or logs out.

## Technical requirements

The current on login code must check if the "Forced 2SV" option is set and whether the user belongs in a user group which has forced 2SV. In this case we override the "don't show this again" flag AND the redirect.

If 2SV is set up we set the "don't show captive setup page" just like we do after a successful 2SV login for the 2SV flag.

The system plugin must check if the "don't show captive setup page" flag is unset / set to false. In this case we need to enforce a captive login to the entire com_loginguard and com_ajax component.

Disabling 2SV for myself must result in the "don't show captive setup page" flag to be reset.

**Comment by nikosdion** [comment]
And done

**Comment by johanpeters** [comment]
how to implement this.. the latest download version (3.0.0) from the akeeba site is from 22-may..

**Comment by nikosdion** [comment]
I finished writing this code about an hour before you asked. The next release is scheduled for September. I'm not making releases when pretty much everyone's on vacation.

If you really want to use the new code before I make a release you can try to make a dev build yourself. If you're not sure how just wait for September. I'm scheduling a mega-release of everything during the first ten days of September.

**Comment by johanpeters** [comment]
Okay.. tnx for the feedback and update... 
i don't know howto build develop.. so i just wait until the next release.. 
thanks for the greate effort.. happy holidays and i am looking forward for this new feature.. so i can implement it and recommend it to al my clients.. 

greetings
