### ISSUE TITLE
[UNDER CONSIDERATION] User 2SV management page in the backend

### ISSUE THREAD

**Issue by nikosdion** [akeeba/loginguard#50]
Joomla does not allow us to add columns or otherwise add information to the Users component's list output. This means that we cannot display whether a user has 2SV enabled in the user list view. You have to click on each one of them which is a pain in the posterior.

Check if it's possible to inject an XML form field in Joomla's Users page. If that's not possible create a simplified Users view in LoginGuard, accessible only under a separate ACL privilege, to display a list of Users and their 2SV status. 

Caveat: on long lists (e.g. 500 users) going through the helper to display the status may not be the brightest idea. Using a JOIN against a COUNT/GROUP BY subquery on the LoginGuard table is probably better for performance since that table is indexed on the user_id anyway.

**Comment by brianteeman** [comment]
If I understand you correctly you want to add some extra information to the user list view to indicate 2sv for each user.

I used a plugin to add an extra button in the list view for resending the activation email. It is code fromm Yannick - maybe it will help https://github.com/brianteeman/AdminApproval/releases/tag/1.0

**Comment by brianteeman** [comment]
Ok. I was just sharing ;)
