### ISSUE TITLE
reset users publish status

### ISSUE THREAD

**Issue by bcordis** [akeeba/loginguard#53]
### Steps to reproduce the issue

Make sure your issue can be reproduced on a new installation of Joomla! without any modified configuration settings or third party extensions. If the issue only occurs with a specific third party extension or configuration setting please specify exactly what triggers it. Always keep in mind that if it can't be reproduced it can't be fixed!

### System information (as much as possible)
* **Joomla! version**: x.y.z
* **Database type**: MySQL, PostgreSQL, SQL Server
* **Database version**: x.y.z
* **Server type**: Apache, NginX, IIS, Lighttpd, LiteSpeed, ...
* **Server version**: x.y.z
* **Hosting company / Local server**: Enter the name of your site's hosting company or the prepackaged local server (e.g. MAMP, XAMPP, WAMPServer, ...) that you're using
* **Am I using HTTPS**: Yes or No
* **Server Operating System**: Windows, Linux, macOS, Don't Know
* **Server Operating System version**: e.g. Windows 10, Ubuntu 16.04, ... Type N/A if it's a live host and you have no idea. 
* **Browser**: Chrome, Firefox, Edge, Internet Explorer, Safari, Opera, ...
* **Browser version**: x.y.z

**Comment by nikosdion** [comment]
If you can't be bothered writing anything sensible I have only one reasonable action to take: close and lock.
