### ISSUE TITLE
How to reset single users 2 step authentication.

### ISSUE THREAD

**Issue by bcordis** [akeeba/loginguard#54]
### Steps to reproduce the issue

Make sure your issue can be reproduced on a new installation of Joomla! without any modified configuration settings or third party extensions. If the issue only occurs with a specific third party extension or configuration setting please specify exactly what triggers it. Always keep in mind that if it can't be reproduced it can't be fixed!

### Expected result
Login into the component page and looking at the user to disable two-step authentication for them or reset them. allowing the end user to log in and re-setup.

### Actual result
No way to be found.

### System information (as much as possible)
* **Joomla! version**: Joomla! 3.8.13 Stable [ Amani ] 9-October-2018 14:00 GMT
* **Database type**: MySQL
* **Database version**: 5.6.34-log
* **Server type**: Apache
* **Server version**: Not available
* **Hosting company / Local server**: DreamHost VPS
* **Am I using HTTPS**: Yes 
* **Server Operating System**: Linux
* **Server Operating System version**: Linux ps20763 3.14.52-vs2.3.6.15-1 #1 SMP Wed Nov 2 10:45:38 UTC 2016 x86_64 
* **Browser**: Chrome
* **Browser version**: Version 69.0.3497.100 (Official Build) (64-bit)

### Additional comments
Searching through all documentation and have not see how to make this happen. Thanks.

**Comment by nikosdion** [comment]
https://github.com/akeeba/loginguard/wiki/The-user-plugin

**Comment by bcordis** [comment]
Also found out they must not be a superuser to disable the this. that is why I was not seeing the tab. Thanks for the help.
