### ISSUE TITLE
ACL problem

### ISSUE THREAD

**Issue by joomlatester** [akeeba/loginguard#58]
### Steps to reproduce the issue

I have administrator group (not super user). This group has access to edit and delete user and access to Akeeba LoginGuard component. 
Despite the settings, the group does not have access to the component.

https://ibb.co/gaKEhq
https://ibb.co/gbU88V

### Expected result

Fix

### System information (as much as possible)
* **Joomla! version**: x.y.z
* **Database type**: MySQL, PostgreSQL, SQL Server
* **Database version**: x.y.z
* **Server type**: Apache, NginX, IIS, Lighttpd, LiteSpeed, ...
* **Server version**: x.y.z
* **Hosting company / Local server**: Enter the name of your site's hosting company or the prepackaged local server (e.g. MAMP, XAMPP, WAMPServer, ...) that you're using
* **Am I using HTTPS**: Yes or No
* **Server Operating System**: Windows, Linux, macOS, Don't Know
* **Server Operating System version**: e.g. Windows 10, Ubuntu 16.04, ... Type N/A if it's a live host and you have no idea. 
* **Browser**: Chrome, Firefox, Edge, Internet Explorer, Safari, Opera, ...
* **Browser version**: x.y.z

**Comment by nikosdion** [comment]
Your issue description is unclear. The pictures are in a language I do not speak.

**Comment by joomlatester** [comment]
I have several groups on the backend:
1. Super administrator (Super user)
2. Administrator
3. Publisher
e.t.c.

1. Super administrator (Has access to the component AdminGuard by default)
2. Administrator
- I set ACL in AdminGuard to Access Administration Interface, Access user list

But this group still cannot access to component and user list.

**Comment by nikosdion** [comment]
Not an issue. Only Super Users have access to com_loginguard _for security reasons_. Disabling someone's 2SV _and_ being able to change their password results in a situation where one user can impersonate another. This is a privacy and security issue. By limiting the component to Super Users (most trusted tier) and only allowing them to disable 2SV for non-Super Users we are circumventing this issue.

Do note that all backend users can go to their profile page and manage their 2SV options. They have to do it either from the Users page or from the front-end. Do NOT use the profile link from the top right corner of the backend page, that's a DIFFERENT functionality in Joomla! which is stupidly labeled the same but it works differently and does NOT allow third party extensions to display content in it.
