### ISSUE TITLE
duplicate backup code presented

### ISSUE THREAD

**Issue by johanpeters** [akeeba/loginguard#60]
i use the latest version.
completly configured.. 

when a user logs in and select different validation option a page is presented with the user configured options to authenticate.
below that, the backup codes...

but the backup codes option  are presented twice
![schermafbeelding 2018-11-12 om 10 37 30](https://user-images.githubusercontent.com/1411354/48338838-fd912280-e666-11e8-9a2f-a64692d15e1d.png)

**Comment by johanpeters** [comment]
when i succesfully logd in.. and look at my user profile (2 factor settings)
there is only one backup.
![schermafbeelding 2018-11-12 om 10 39 16](https://user-images.githubusercontent.com/1411354/48338968-51037080-e667-11e8-9c4a-2a91b42af76a.png)

**Comment by nikosdion** [comment]
Cannot reproduce.

**Comment by johanpeters** [comment]
i have checked a clean install on basis joomla 3.9 installation.
to reproduce..
1. install joomla 3.9
2. install Akeeba Loginguard
3. configure Akeeba loginguard (authenticator app)
4. user (admin) force use
5. user (admin) configure two step (authenticator app)
6. login backend
7. on two step verification select a different method
![schermafbeelding 2018-11-12 om 23 51 22](https://user-images.githubusercontent.com/1411354/48380185-1802e480-e6d7-11e8-8878-7e3919a9d340.png)

8. this page shows..
- authenticator app
- Backup codes
- Backup codes (Emergency Access).
![schermafbeelding 2018-11-12 om 23 51 53](https://user-images.githubusercontent.com/1411354/48380196-1fc28900-e6d7-11e8-87b5-55fb9f943a10.png)
the link of the two Backup Codes are the same.. 
i don't understand.. is this how it works?.. 
Iff so.. what is the different between backup codes and backup code (Emergency Acces).
the link is the same.. and the user (on user details) has only backup codes.. 

after login.. on user details - two 
![schermafbeelding 2018-11-12 om 23 53 58](https://user-images.githubusercontent.com/1411354/48380269-56989f00-e6d7-11e8-9cd1-5f5350b20056.png)

**Comment by johanpeters** [comment]
please reopen or answer if this is suppose to be..

**Comment by johanpeters** [comment]
okay... thanks.. so it's a known issue.. and will be fixed in the future.. 
than this can be moved to known issues.. list for thinks to fix..

**Comment by nikosdion** [comment]
Thank you for stating the obvious :+1:
