### ISSUE TITLE
conflict with joomla 3.9 privacy suit

### ISSUE THREAD

**Issue by johanpeters** [akeeba/loginguard#61]
when i force to use loginguard for users.
and when privacy suite in joomla 3.9 is enabled (accept privacy terms).. 
the login proces gifs error 500 (loops).. 
when i disable accept privacy terms everything works fine.. 

Existing users.. i  wil test to see what the results are with new created user.

reproduce..
Good
1. with privacy plugin disabled.
1. login with username and password
2. two step verify
3. loggedin.

Error
1. with privacy plugin enabled
1. login with username and password
2. no two step page. .but error page (loops)
3. when i hit pageback in browser.. two step pages shows with error message (you need to accept privacy terms)..

asspected result.
1. username and password
2. privacy terms accept
3. two step page

**Comment by nikosdion** [comment]
This issue has already been addressed, see https://github.com/akeeba/loginguard/commit/2fcf4fe5893e5727b64f27ec36544fd00a4409fe

**Comment by johanpeters** [comment]
UPDATE:
error is: ERR_TOO_MANY_REDIRECTS
when forced use of 2FA and
Joomla privacy.. need to accept terms

**Comment by nikosdion** [comment]
As I already said, this has been fixed. If you could please install version 3.3.0 you will see that this problem no longer occurs. Please do not report an issue I have already fixed, especially when there is a published release with the fix. Same thing applies for insisting after I've told you it's fixed. Thank you.

Caveat: you need to QUIT your browser and re-open it. Browsers cache the redirections.

**Comment by johanpeters** [comment]
okay.. thanks.. 
i use the update feature of joomla to keep up to date.. 
the latest version is 3.0.2.. so  .. i do need to download 3.3.0 of github??

**Comment by nikosdion** [comment]
Sorry, I meant 3.0.3. You can grab it from here https://github.com/akeeba/loginguard/releases/tag/3.0.3
