### ISSUE TITLE
SEF url

### ISSUE THREAD

**Issue by johanpeters** [akeeba/loginguard#62]
i have enabled SEF urls in Joomla.
when a user logs in.. the loginguard url's are not SEF..
i tried to create a systemlink menu item but its ignored.
the url for the two step verify
https://~domain~/component/loginguard/?view=captive
i would like to have this SEF..  something like
https://~domain~/2nd-step

and for select other method
https://~domain~/component/loginguard/?view=captive&task=select
something link
https://~domain~/2nd-step-method

**Comment by nikosdion** [comment]
You cannot do that. It is by design. I am not going to write a SEF router for LoginGuard.
