### ISSUE TITLE
logoff not working with Community builder login

### ISSUE THREAD

**Issue by johanpeters** [akeeba/loginguard#63]
On a website without Community builder (free).. 
on the second page you have the option to fill in your 2 step code, change method and logout.

When you click on logout the user is logged of and the public website is shown.

with community builder.
the 2nd page is also working.. just like a normal website.. 
but when the user don't fill in 2nd key or change method en proced but choice to logoff the page is getting reloaded to the 2nd step.. user is not logged off.

**Comment by nikosdion** [comment]
You are continuously wasting my time with pointless issues. I am not your free help desk. You have been banned from filing any more issues on any Akeeba project on GitHub.
