### ISSUE TITLE
Disable U2F on unsupported browsers

### ISSUE THREAD

**Issue by nikosdion** [akeeba/loginguard#66]
Currently, the U2F plugin is enabled on all browsers. This means that we let people:

- try to register a security key on unsupported browsers. This results in errors but the user does not know why. Since we have to rely to the browser's JavaScript object for U2F we can't do much in the department of improved errors for the user.
- try to login with a security key on unsupported browsers. This always fails and generates a popup error alert. Trying to select a different method results in the same popup error alert on the method selection page (a consequence of using the aforementioned JS object). Even worse, if your _only_ two step verification method is a security key you are effectively logged out of your account.

The only sensible thing to do is disable the U2F plugin for both key registration (2SV setup) and verification (2SV captive page) on unsupported browsers. The caveat is that if your only 2SV method is a security key then it can be bypassed easily by spoofing the user agent.

Looking into that I determined that only Google Chrome 38+ and Opera 41+ properly support 2SV on Windows, macOS, Linux and Android. Anything else does not support 2SV.

First, you might say, but Firefox _does_ support 2SV, right? Yes, well, actually not really and very well. More than three years since its introduction, U2F is still an experimental feature which requires flipping a special flag in a user-unfriendly way. Even if you do that, it doesn't really work. Only security keys registered with Firefox will work. Moreover, if you register a key in the backend it cannot be used in the frontend and vice-versa. This has to do with how FF calculates the appId of the FIDO U2F specification. On top of that, it allows insecure usage of security keys on plain old HTTP sites. There are so many things wrong with this implementation we cannot continue to support it, especially since all the bug reports in Firefox' bug tracker seem to be effectively stonewalled. FF has implemented WebAuthn instead and _that's_ the standard they want to promote, U2F be damned.

Second, you might wonder "what about other browsers on Android"? Well, U2F support is not part of Android proper but a feature of Google Authenticator. It will only talk with Chromium browsers, i.e. Google Chrome and Opera (not Mini, the full Opera). Anything else, like Edge or Firefox, will simply not be able to use U2F.

Finally, you might wonder what about iOS support. Simply put, iOS and U2F don't work together. U2F hardware security keys do not implement HID (Human Interface Device). They require raw access to the USB host for the authenticating application to talk to them in their own protocol. iOS does not implement a generic USB host. All low level USB interaction takes place at the OS level, not the application level (applications run sandboxed). Since iOS does not speak the U2F protocol you have no U2F support. This also explains why you have YubiKey OTP support instead; YubiKey connects to your iOS device either as a USB keyboard (using the USB-C/Lightning to USB-A dongle) or the OTP is read with a third party NFC reader since the YubiKey pretends to be a standard read-only NFC tag.

So, the bottom line is that you can only have U2F on Chrome and Opera. Everybody using a different browser OR iOS should have a fallback method, e.g. TOTP. If you do not have a fallback verification method you will be able to log in _without_ verification if you use an unsupported browser.

**Comment by Vednier** [comment]
You should not wait for U2F in firefox to be implemented, because they already switched to Webauthn (its turned On by default) and FIDO2, which is improved and backward compatible (in term of usage of U2F dongles). Google supports Webauthn too and even Microsoft implemented Webauthn support in Windows hello. Maybe you should work on Webauthn? Thank you for U2F support, but it came way too late for any serious usage.

**Comment by nikosdion** [comment]
You are wrong. U2F is second factor, Webauthn is authentication. They are not interchangeable. Google it. 

Old FIDO U2F keys are not forward compatible with Webauthn. New FIDO2 keys are compatible with both Webauthn and U2F. Your assertion is wrong, obviously because you never owned the hardware it bothered trying to implement Webauthn support (I did both). 

Webauthn is NOT something you could put in LoginGuard. It’s something to be implemented as an authentication anf user plugin. However, Joomla does not support authentication schemes which don’t use a username and password. You’d have to go with a gnarly workaround like I did in SocialLogin which I discontinued. 

To make it clear.  No, I’ll not implement Webauthn at this point. It’s impractical for me and would cause trouble for my users (you need to register separately per device, browser and hardware key on each site; if you lose/reset one of these you’re locked out of your site). It’s also ABSOLUTELY NOT something that can ever remotely be mistaken as a second factor, therefore discussing it in this repo is nonsense. If anything, Webauthn means to get rid of the need for a second factor. Have you even read the information on their site?
