### ISSUE TITLE
Create a plugin for "Duo Security"

### ISSUE THREAD

**Issue by depebo** [akeeba/loginguard#69]
# Enhancement
## New Plugin Request

Add plugin to allow use of Duo Security. General information on Duo architecture is here:
https://duo.com/docs/duoweb

PHP example: https://github.com/duosecurity/duo_php

WordPress example: https://github.com/duosecurity/duo_wordpress

Happy to assist in coding.

**Comment by nikosdion** [comment]
I am currently very busy with other work. Once I have some more time (probably around July or August) I will look into this.

**Comment by depebo** [comment]
Thank you. Sent you an email - let me know if I can assist in the meantime.

**Comment by nikosdion** [comment]
I checked what Duo Security is. Sorry, it's not a good candidate for LoginGuard integration. I'll simplify it for you. They do **user authentication**, they are not a method for two step verification. An integration with it would make more sense as a separate product. It's the same concept as my passwordless login plugin. 

For this reason I am going to close this issue as "invalid".

**Comment by depebo** [comment]
Thanks for your feedback, sorry to hear you closed this issue.

It is not the same as passwordless, as before requesting Duo verification the user must successfully authenticate using Joomla! username/password. Only after that additional form is displayed allowing user to select second preferred Auth method (push, call, sms, or code entry).
Your "captive login" with the ability to plug-in seemed like a perfect place to do that. The appeal of Duo: users can enable in on Joomla! easier than other forms of authentication (all setup is done by administrator on Duo, removing this task from Joomla users).

**Comment by nikosdion** [comment]
First of all, Duo is marketed as SSO and MFA on their site. 

Yes, you can use it only as MFA, for a fee. LoginGuard WHICH DOES EXACTLY THE SAME THING is free of charge. 

I understand you want to pay someone else a large recurring sum to do what takes you, gee, dunno, THREE MINUTES? OK, it’s your choice.

But asking me to spend my free of charge time to implement a competitive solution that substitutes my product so someone else can make money and I get neither financial compensation nor users? Why would I do that?!

**Comment by depebo** [comment]
Thank you for your comment.
Duo is free for up to 10 user. Users are using the same device in multiple sites/remote desktops without additional setup in each location. In my post about a month ago I have offered help to write plug-in for LoginGuard.
Will now do as you suggested.

**Comment by nikosdion** [comment]
As I said, I have two issues with Duo Security.

1. It's an alternative to LoginGuard, not a second verification factor. It's doing what LoginGiard is doing.

2. As you said, it's only free for up to 10 users. Therefore, if you want to use it on anything but a tiny personal site you will practically end up paying for what LoginGuard does for free.

And let's not forget that it does not give you the flexibility LoginGuard provides such as forcing or preventing user groups from using 2SV or deciding which Joomla login methods should use 2SV.

Finally, if you decide to migrate off them you're outta luck. You will have to disable 2SV completely and start from scratch. Not to mention that you can't even migrate core TFA to Duo, something LoginGuard has been doing since its very first beta...

**Comment by depebo** [comment]
My issue is that users need some form of 2FA for MS Remote Desktop. And they also need it for website admin login. Duo allows one admin to manage others and does push notifications (as well as voice and sms and OAuth), which simplifies the process. The link between user and device is on Duo side, managed centrally, this way users don't need to register their MFA devices on each desktop/site. There are other useful functions like temporary disable MFA, access log, device status, etc..
Do you you have plans to extend LoginGuard to Remote Desktop?

**Comment by nikosdion** [comment]
You can afford MS Windows licenses. You can afford the bandwidth for remote desktop connections (not exactly what I'd call a lightweight application). You want a security solution that works across your organization's entire IT infrastructure. You mentioned Duo Security features which are only available on their paid tier. _You have an IT budget._

You are not interested in website security for those who can't afford an enterprise solution, the people I stated are my target audience for LoginGuard. You just want someone to figure out how to complete your enterprise deployment of Duo Security by adding it to your Joomla site. Fair enough, you have a valid use case there. What I don't understand is why you're trying to make me work for free when, clearly, you guys have the money to hire us to do this for a reasonable fee.

**Comment by depebo** [comment]
Every Windows Server comes with 2 concurrent user RDP licences, small cloud deployed server instance is affordable even for small organisations, bandwidth is responsibility of end user. This is a very small budget solution for a small organisation.
I wanted to develop plug-in myself (see my private e-mail to you), thought others may benefit from it as well (hence this ticket). Thought LoginGuard was a suitable starting point.
Never my intention to make you work for free - send me your quote, so we can discuss further, if you are interested.

**Comment by nikosdion** [comment]
Can you please use the contact form on AkeebaBackup.com? I can’t find your previous email – deleted due to GDPR requirements is my guess :/
