### ISSUE TITLE
update url is not working

### ISSUE THREAD

**Issue by johanpeters** [akeeba/loginguard#85]
Please read the README.md in the repository's root and the support resources before submitting an issue.

### Steps to reproduce the issue
just regulier Joomla update proces.. update url unable to open URL: https://raw.githubusercontent.com/akeeba/loginguard/master/update/pkg_loginguard_updates.xml
Be specific. You may link to one or more screenshots or a video as long as it's not the only clue you leave. Use words to describe what happens.

### Expected result

What you believed should have happened following the steps you outlined above.
update to version 3.3.1

### Actual result
unable to update using regular joomla update
What actually happened.

### Troubleshooting already performed

Please tell us about any troubleshooting you already performed and its results.

#### Mandatory information

Issues without this information can not and _will not_ be replied to.

* **Joomla! version**: x.y.z
* **PHP version**: x.y.z
* **Am I using HTTPS**: Yes or No
* **Server Operating System**: Windows, Linux, macOS, Don't Know
* **My device's Operating System**: Windows, Linux, macOS, iOS, Android...
* **My device's Operating System version**: e.g. macOS Mojave
* **Browser**: Chrome, Firefox, Edge, Internet Explorer, Safari, Opera, ...
* **Browser version**: x.y.z

#### Good to have information

You can skip some or all of this information. However, the more information you provide the faster and better we can help.

* **MySQL version**: x.y.z
* **Server type**: Apache, NginX, IIS, Lighttpd, LiteSpeed, ...
* **Server version**: x.y.z
* **Hosting company / Local server**: Enter the name of your site's hosting company or the prepackaged local server (e.g. MAMP, XAMPP, WAMPServer, ...) that you're using
* **Server Operating System version**: e.g. Windows 10, Ubuntu 16.04, ... Type N/A if it's a live host and you have no idea.

**Comment by johanpeters** [comment]
Manual installation of 3.3.1 also not working..
Installer: :Installeren: file does not exist /home/ijssel1q/public_html/tmp/install_5ef0f8615b575/loginguard-3.3.1/component/backend/vendor
Component Update: copy beheergedeelte-bestanden failed.

**Comment by johanpeters** [comment]
i tried several site's.. al same issue.. but i also see several other github extentions with update issues... something wrong on github or?

**Comment by johanpeters** [comment]
downloaded from
https://www.akeebabackup.com/download/official/loginguard/3-3-1.html

manual installation succesfull.. 
check joomla updates still gives update error..

**Comment by nikosdion** [comment]
The update URL for previous versions of LoginGuard, SocialLogin and Engage no longer works after we renamed the branch from `master` to `main`. Furthermore, you'll notice that we moved all of our downloads and updates to our own CDN.

Tomorrow morning, our time, we'll be making an announcement asking users of this software to update it manually.

**Comment by johanpeters** [comment]
Hello Nicholas.Thank you for your Quick response.. I Will check and updates from your official website .. and change the update URL for the products.. I have check and change 25 websites.. Should the pkg of the website have the correct update URL..  or do we have to change IT manually?Verzonden vanaf mijn Samsung Galaxy-smartphone.
-------- Oorspronkelijk bericht --------Van: "Nicholas K. Dionysopoulos" <notifications@github.com> Datum: 22-06-2020  20:59  (GMT+01:00) Aan: akeeba/loginguard <loginguard@noreply.github.com> Cc: johanpeters <j.peters@itics.nl>, Author <author@noreply.github.com> Onderwerp: Re: [akeeba/loginguard] update url is not working (#85) 
The update URL for previous versions of LoginGuard, SocialLogin and Engage no longer works after we renamed the branch from master to main. Furthermore, you'll notice that we moved all of our downloads and updates to our own CDN.
Tomorrow morning, our time, we'll be making an announcement asking users of this software to update it manually.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/akeeba/loginguard/issues/85#issuecomment-647713536",
"url": "https://github.com/akeeba/loginguard/issues/85#issuecomment-647713536",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by nikosdion** [comment]
Just install the new package. It will add the new update site (update URL). The old one will eventually get disabled automatically since it fails to load. A future update –or installing the new version twice– will delete the old update URL.
