### ISSUE TITLE
Automating "Authentication Code by SMS"

### ISSUE THREAD

**Issue by nobicycle** [akeeba/loginguard#90]
**Is your feature request related to a problem? Please describe.**

 "Your Second Step" is unnecessary for SMS because Phone can be pulled from the user profile

**Describe the solution you'd like**

New Component Options

- Title
- Phone selector from a list of custom fields.
- Check Box - Automate SMS Second Step.

If the checkbox was checked and if Title and Phone are valid data, then LoginGuard has all that is required to skip the "Add a second step" for SMS Verification.

**Describe alternatives you've considered**

Actually I am thinking about how to verify progressively  phone numbers of registered users. 
With LoginGuard it could be done via-

1. Allowing SMS verification only.
2. Adding users to a 'CheckSMS' group and adding that group to the Force TSV For Certain Groups.
3. Removing users from CheckSMS groups when they have next logged in.

**Why do you think this is relevant to people other than you**

There is no phone verification app available now that ACYMAIL have pulled the plug on ACYSMS.
Phone verification is an important security method  to reduce fraud on  websites conducting transactions. It is of general application. It might become a commercial app for Akeeba if you charged a more modest price than ACYMAIL (100 EUR )

**Comment by nikosdion** [comment]
LoginGuard protects logging into your site. Besides something they know (username and password), users must also use something they have such as a security key, smartphone, phone number etc.

What you want is verify someone is in possession of a phone number **once**.

There is absolutely no correlation between what you want and what LoginGuard does. What you are asking is not a feature, it is **a completely different extension altogether** I am not interested in writing. Sorry.

**Comment by nobicycle** [comment]
Understood.
