### ISSUE TITLE
The Methods configuration page is exposed to the public

### ISSUE THREAD

**Issue by asiby** [akeeba/loginguard#95]
Hi guys

I am not sure if this should be considered as a bug report or a security vulnerability. Either way, it would be nice to solve it. I am a volunteer at large. I use Joomla among other CMS solutions.

The issue I am reporting today is that I have noticed that when the Akeeba LoginGuard is installed, it becomes possible to navigate to [](https://example.com/component/loginguard/?view=Methods&task=display&layout=firsttime) or [](https://example.com/component/loginguard/?view=Methods&task=display) without being logged in. This will show a page that is not showing any 2FA method, but it will still render the layout of the Methods page. I believe that it would be best to simply send them to the login page with an "unauthorized" response.

### Steps to reproduce the issue

Assuming that the root URL of your Joomla installation is https://example.com/

1. Install and enable LoginGuard
2. Do no log in.
3. Type the following address in the browser's address bar: https://example.com/component/loginguard/?view=Methods&task=display&layout=firsttime
4. You should see something unexpectedly being renderer instead of being redirected to the log in page.

### Expected result

The expect result is to not have access to anything and be redirected to the login page.

### Actual result

You will have a 2FA Methods configuration page trying to be rendered by LoginGuard as shown on the screenshot.

![Screen Shot 2020-11-13 at 8 04 30 PM](https://user-images.githubusercontent.com/455674/99134387-75460f00-25eb-11eb-9674-78baa734d9b3.png)

### Troubleshooting already performed

N/A

### System information

N/A

#### Mandatory information

* **Joomla! version**: 3.9.22
* **PHP version**: 7.3.24
* **Am I using HTTPS**: No
* **Server Operating System**: Linux
* **My device's Operating System**: macOS
* **My device's Operating System version**: macOS Catalina
* **Browser**: Chrome
* **Browser version**: 86.0.4240.193

**Comment by asiby** [comment]
I have just discovered this today. I am working on a possible pull-request.

**Comment by nikosdion** [comment]
This happens because of leftover code from when we were using Joomla's MVC instead of our own framework. The display task shouldn't have been whitelisted in the Methods controller, thereby forcing it to go through the main() method.

In any case it's not a security issue because all controls on that page are unusable. All individual methods have access control to only allow logged in users to access them. It's not even a good way to determine whether LoginGuard is installed; checking for an extension's JS/CSS files is the surefire way to determine if it's installed and if so which version (or at least which version _range_).

No need to make a PR. I know where and what the problem is; I just committed a fix.

**Comment by nikosdion** [comment]
Coffee hasn't kicked in yet. I forgot to thank you for bringing this to my attention. How rude of me.

**Thank you** for bringing this to my attention 😄

**Comment by asiby** [comment]
You are very welcome. I have to say that I was pleasantly surprised about the quick response time. Thank for this amazing package.

**Comment by nikosdion** [comment]
You're welcome!

I will be publishing a new version probably this week, based on available time. I have other software releases in the queue before LoginGuard.

Have a great evening!

**Comment by asiby** [comment]
That's fantastic. I have one question that I couldn't find answers for in your documentations. I will post it as a general question. Hopefully the answer will be straightforward. 🙂

Have a great evening as well!
