### ISSUE TITLE
3.3.9 Clean install failure

### ISSUE THREAD

**Issue by WimVDK** [akeeba/loginguard#99]
Please read the README.md in the repository's root and the support resources before submitting an issue.

### Steps to reproduce the issue

Setup fresh joomla environment. Database server MariaDB 
Possibly related (not sure) Install Akeeba admin tools, setup htaccess and activate "Set the UTF-8 characterset as the default".
Attempt to install latest loginguard release 3.3.9

### Expected result

Component installed as normal

### Actual result
Install failure with 
** You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ' ) ENGINE=InnoDB DEFAULT COLLATE=utf8_general_ci' at line 11
Package install: An error occurred during installation of an extension: com_loginguard.zip

### Troubleshooting already performed

Tried installing component over the top multiple times. Each time failed. Oddly enough installing the last version i had on my hard drive (being 3.2.1) prior to downloading 3.3.9, 3.2.1 installed just fine immediately. So i figured, lets try installing 3.3.9 over the top immediately, this DID "WORK" and no install failed warning.

However going into extension manager only 1 entry is found "LOGINGUARD 3.3.9" and no related plugins, system etc like exists after installing 3.2.1.  The component entry under component manager also shows the language string placeholder "COM_LOGINGUARD" instead of the actual component value "Akeeba LoginGuard" and clicking on it results in 404 component not found.

SU access can be provided

#### Mandatory information

Issues without this information can not and _will not_ be replied to.

* **Joomla! version**: 3.9.24
* **PHP version**: 7.4.15
* **Am I using HTTPS**: Yes
* **Server Operating System**: Linux
* **My device's Operating System**: Windows
* **My device's Operating System version**: 10 Pro x64
* **Browser**: Chrome, Firefox, 
* **Browser version**: 85.0.2

#### Good to have information

You can skip some or all of this information. However, the more information you provide the faster and better we can help.

* **MySQL version**: 5.5.5-10.2.36-MariaDB 
* **Server type**: Apache
* **Server version**: Linux <snip> 3.10.0-1160.6.1.el7.x86_64 #1 SMP Tue Nov 17 13:59:11 UTC 2020 x86_64

* **Hosting company / Local server**: Myself
* **Server Operating System version**: See above

### Additional comments
![afbeelding](https://user-images.githubusercontent.com/14872315/107879102-2d2ed500-6ed7-11eb-97fa-3bedb662a43b.png)

**Comment by nikosdion** [comment]
It sounds like you have not enabled InnoDB in your MariaDB installation. Do note that both MySQL and MariaDB come with InnoDB enabled by default. You'd have to manually sabotage your server to trigger this error.

**Comment by WimVDK** [comment]
I'm only a small time hoster for friends & family. The server is running plesk on a VPS. Didn't change anything. Curious though why 3.2.1 would install (and be fully working), then installing 3.3.9 over the top breaks it.

If PhpMyAdmin is working properly InnoDB is enabled. Belong a 2 images that would suggest everything is working just peachy on that part.

![afbeelding](https://user-images.githubusercontent.com/14872315/107880051-b268b880-6edc-11eb-8466-32bdd73ce80a.png)
![afbeelding](https://user-images.githubusercontent.com/14872315/107880136-40dd3a00-6edd-11eb-88ac-5ae3587d56d3.png)


I would have posted on the akeeba as i can hide the active url there (as this is a fesh setup for a new site) and provide credentials securely. Obviously not going to post an admin su on public github

**Comment by nikosdion** [comment]
There seems to have been a problem since version 3.3.7 with new installs. I published version 3.3.10 which fixes it just now.

**Comment by WimVDK** [comment]
Happy to confirm the fix. Just to make sure there weren't any conflicts, i uninstalled 3.3.0, then fresh installed 3.3.10. Install completed first try! Thanks for the quick fix!

**Comment by nikosdion** [comment]
Thank you for reporting this and giving me the information I needed to reproduce it!
